### ISSUE TITLE
push notifications dont work 

### ISSUE THREAD

**Issue by ibrokemypie** [ibrokemypie/mastalab#27]
```
E/JobExecutor: Crashed job{id=1, finished=true, result=FAILURE, canceled=false, periodic=true, class=NotificationsSyncJob, tag=job_notification}
    java.lang.NumberFormatException: For input string: "5c1882a8d8e2b74e05814133"
        at java.lang.Long.parseLong(Long.java:594)
        at java.lang.Long.parseLong(Long.java:636)
        at fr.gouv.etalab.mastodon.jobs.NotificationsSyncJob.onRetrieveNotifications(NotificationsSyncJob.java:247)
        at fr.gouv.etalab.mastodon.jobs.NotificationsSyncJob.callAsynchronousTask(NotificationsSyncJob.java:135)
        at fr.gouv.etalab.mastodon.jobs.NotificationsSyncJob.onRunJob(NotificationsSyncJob.java:78)
        at com.evernote.android.job.Job.runJob(Job.java:124)
        at com.evernote.android.job.JobExecutor$JobCallable.runJob(JobExecutor.java:181)
        at com.evernote.android.job.JobExecutor$JobCallable.call(JobExecutor.java:166)
        at com.evernote.android.job.JobExecutor$JobCallable.call(JobExecutor.java:149)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
```

havent been touched

**Comment by ghost** [comment]
OK. I will do that.

**Comment by ibrokemypie** [comment]
awesome, thanks!
