### ISSUE TITLE
Crash when refreshing status twice

### ISSUE THREAD

**Issue by ibrokemypie** [ibrokemypie/mastalab#38]
```
E/Parcel: Class not found when unmarshalling: 
    java.lang.ClassNotFoundException: Invalid name: 
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:453)
        at android.os.Parcel.readParcelableCreator(Parcel.java:2811)
        at android.os.Parcel.readParcelable(Parcel.java:2765)
        at fr.gouv.etalab.mastodon.client.Entities.Status.<init>(Status.java:141)
        at fr.gouv.etalab.mastodon.client.Entities.Status$1.createFromParcel(Status.java:206)
        at fr.gouv.etalab.mastodon.client.Entities.Status$1.createFromParcel(Status.java:203)
        at android.os.Parcel.readParcelable(Parcel.java:2774)
        at android.os.Parcel.readValue(Parcel.java:2668)
        at android.os.Parcel.readArrayMapInternal(Parcel.java:3037)
        at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:288)
        at android.os.BaseBundle.unparcel(BaseBundle.java:232)
        at android.os.Bundle.getParcelable(Bundle.java:940)
        at fr.gouv.etalab.mastodon.activities.ShowConversationActivity.onCreate(ShowConversationActivity.java:107)
        at android.app.Activity.performCreate(Activity.java:7145)
        at android.app.Activity.performCreate(Activity.java:7136)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2932)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3087)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1817)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6723)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:495)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:859)

```

might only be from notifications?

i dont know how the application class works
seems the error is java.lang.ClassNotFoundException: Invalid name: 
i dont know how to deal with this

**Comment by ghost** [comment]
It'a an issue with a parcel. It's due to `application` property in Status Entity.

**Comment by ibrokemypie** [comment]
i see that, but i cant tell what the problem is
right now it should always be an empty Application() sinnce misskey does not have a website field
https://github.com/ibrokemypie/mastalab/commit/d3b876e0ebcbe9599ad6f790f664ec680a9b9242

**Comment by ghost** [comment]
I can't reproduce on my end :(

**Comment by ibrokemypie** [comment]
exact steps were as follows:
write a status in the app
have someone favourite it
open the status from the notification in the notifications tab (after they fav'd it)
pull down to refresh, wait, thenn pull down again
